from classesWordRootType import Word

w = input()
a = Word(w)
print('1. ', a)
b = a.get_root()
print('2. ', b)
c = a.get_type()
print('3. ', c)
print('4. ', b.get_type())
d = b.get_words()
print('5. ', d)
e = list(d)
print('6. ', e)
f = e[0]
print('7. ', f)
print('8. ', f.get_root())
print('9. ', f.get_type())
g = c.get_roots()
print('10. ', g)
h = c.get_words()
print('11. ', h)
i = list(g)
j = i[0]
print(j)
print('12. ', j.get_words())
print('13. ', j.get_type())
k = list(h)
l = k[0]
print(l)
print('14. ', l.get_root())
print('15. ', l.get_type())
print('16. ', a.get_root_synonyms())
print('17. ', a.get_norma())
print('18. ', b.get_typeSynonyms())
print('19. ', a.get_functional_synonyms())